image: bitwalker/alpine-elixir-phoenix:latest

services:
  - postgres:latest

variables:
  POSTGRES_DB: "macros_api_test"
  POSTGRES_HOST: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix deps.get
  - mix ecto.create
  - mix ecto.migrate

mix:
  script:
  - mix test
  - mix credo --strict

